version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    enviroment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  redis:
    image: "redis:alpine"